# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.ThirdParty'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.ThirdParty'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.ThirdParty'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='next_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='forecast.Statement'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='previous_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev', to='forecast.Statement'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forecast.TransactionMethod'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payee', to='forecast.ThirdParty'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payer', to='forecast.ThirdParty'),
        ),
    ]
